export const COPY = {
  problem: "学习，本就不该千篇一律。",
  sameAnswer: "同一个答案",
  premise: "如果 AI 能真正理解你如何学习？",
  goal: "我想真正理解 PCA，并能够独立做题。",
  stateDecides: "State decides next.",
  pcaHint: "寻找数据变化最大的方向",
  variance: "variance",
  formula: "Var(X) = max",
  formulaHint: "主成分保留变化最显著的方向。",
  practice: "Try it yourself",
  question: "PCA 首先寻找什么？",
  wrong: "可解释的误区，也是一条学习证据。",
  oldNext: "Next: Advanced exercise",
  newNext: "Next: Visual explanation",
  philosophy1: "Everything is a Skill.",
  philosophy2: "State decides next.",
  tagline: "AI 学习，因你而变。",
} as const;
