import type { LingxiAttachmentRef, LingxiTaskContextOptions } from '@/lib/api/domains/agent-tasks'
import type { LingxiTaskTransport } from '@/lib/lingxi/lingxi-task-transport'
import {
  buildInteractionAnswerRequest,
  type LingxiV1InteractionAnswerRequest,
  type LingxiV1SubmittedAnswer,
  type LingxiV1ThreadModel,
} from '@/lib/lingxi/stream/turn-model'
import type { ChatContext } from '@/stores/panel'
import type { FileAttachmentForApi } from '../../types'
import { attachmentRefs, contextOptions, requestMessage } from './context-controller'

/** The two transport commands a task thread can accept from the chat surface. */
export type TaskCommand =
  | {
      kind: 'create'
      prompt: string
      attachments: LingxiAttachmentRef[]
      options: LingxiTaskContextOptions
    }
  | {
      kind: 'send'
      taskId: string
      message: string
      attachments: LingxiAttachmentRef[]
      options: LingxiTaskContextOptions
    }

export interface TaskCommandInput {
  /** Missing/blank means this message starts a new durable task. */
  taskId?: string | null
  message: string
  attachments?: FileAttachmentForApi[]
  contexts?: ChatContext[]
  /** Caller-owned stable key; retries must reuse the same value. */
  idempotencyKey: string
}

/** A narrow transport boundary keeps command construction independent of React and API globals. */
export type TaskCommandTransport = Pick<LingxiTaskTransport, 'createTask' | 'sendMessage'>

export type TaskCommandResult =
  | { kind: 'created'; taskId: string; status: string }
  | { kind: 'sent'; taskId: string; status: string }

/**
 * Build the command without touching transport, router or UI state.
 *
 * The normalized prompt is shared by create and send so context serialization
 * cannot drift between the first message and a follow-up.  A null result is
 * the explicit no-op for an empty message.
 */
export function buildTaskCommand(input: TaskCommandInput): TaskCommand | null {
  const content = input.message.trim()
  if (!content) return null

  const prompt = requestMessage(content, input.contexts)
  const attachments = attachmentRefs(input.attachments)
  const options: LingxiTaskContextOptions = {
    ...contextOptions(input.contexts),
    idempotencyKey: input.idempotencyKey,
  }
  const taskId = input.taskId?.trim()

  if (!taskId) {
    return { kind: 'create', prompt, attachments, options }
  }
  return { kind: 'send', taskId, message: prompt, attachments, options }
}

/** Execute an already-decided command. The caller owns optimistic state and navigation. */
export async function executeTaskCommand(
  command: TaskCommand,
  transport: TaskCommandTransport
): Promise<TaskCommandResult> {
  if (command.kind === 'create') {
    const result = await transport.createTask(command.prompt, command.attachments, command.options)
    return { kind: 'created', taskId: result.id, status: result.status }
  }

  const result = await transport.sendMessage(
    command.taskId,
    command.message,
    command.attachments,
    command.options
  )
  return { kind: 'sent', taskId: command.taskId, status: result.status }
}

/** Build and execute one ordinary learner message in one injectable operation. */
export async function runTaskCommand(
  input: TaskCommandInput,
  transport: TaskCommandTransport
): Promise<TaskCommandResult | null> {
  const command = buildTaskCommand(input)
  return command ? executeTaskCommand(command, transport) : null
}

export interface InteractionAnswerCommand extends LingxiV1InteractionAnswerRequest {
  taskId: string
  /** Stable key generated by the caller for this answer attempt. */
  idempotencyKey: string
}

export interface InteractionAnswerInput {
  taskId?: string | null
  model?: LingxiV1ThreadModel | null
  submitted: LingxiV1SubmittedAnswer[]
  idempotencyKey: string
}

export interface InteractionAnswerTransport {
  answerInteraction(
    taskId: string,
    interactionId: string,
    answers: LingxiV1InteractionAnswerRequest['answers'],
    explicitIdempotencyKey: string
  ): Promise<{ status: string; interactionId: string }>
}

/**
 * Decide whether a typed card owns the submission. Null means no open blocking
 * V1 interaction (or an empty/invalid batch), so the UI may fall back to a
 * normal message. No state is changed by this function.
 */
export function buildInteractionAnswerCommand(
  input: InteractionAnswerInput
): InteractionAnswerCommand | null {
  const taskId = input.taskId?.trim()
  if (!taskId || !input.model) return null

  const request = buildInteractionAnswerRequest(input.model, input.submitted)
  if (!request) return null

  return {
    ...request,
    taskId,
    idempotencyKey: input.idempotencyKey,
  }
}

/** Execute a structured answer; errors intentionally propagate to the hook boundary. */
export async function executeInteractionAnswerCommand(
  command: InteractionAnswerCommand,
  transport: InteractionAnswerTransport
): Promise<{ status: string; interactionId: string }> {
  return transport.answerInteraction(
    command.taskId,
    command.interactionId,
    command.answers,
    command.idempotencyKey
  )
}

/** Build and execute a typed interaction answer in one injectable operation. */
export async function runInteractionAnswer(
  input: InteractionAnswerInput,
  transport: InteractionAnswerTransport
): Promise<{ status: string; interactionId: string } | null> {
  const command = buildInteractionAnswerCommand(input)
  return command ? executeInteractionAnswerCommand(command, transport) : null
}

export interface TaskControllerDependencies {
  task: TaskCommandTransport
  interaction: InteractionAnswerTransport
}

/** Convenience facade for hook composition; it owns no mutable state. */
export function createTaskController(dependencies: TaskControllerDependencies) {
  return {
    buildTaskCommand,
    executeTaskCommand: (command: TaskCommand) => executeTaskCommand(command, dependencies.task),
    runTaskCommand: (input: TaskCommandInput) => runTaskCommand(input, dependencies.task),
    buildInteractionAnswerCommand,
    executeInteractionAnswerCommand: (command: InteractionAnswerCommand) =>
      executeInteractionAnswerCommand(command, dependencies.interaction),
    runInteractionAnswer: (input: InteractionAnswerInput) =>
      runInteractionAnswer(input, dependencies.interaction),
  }
}
