"""LingxiLearn V1 initial schema.

Revision ID: 0001
Revises: none
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learners',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_registry',
    sa.Column('skill_id', sa.String(length=160), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('preconditions', sa.JSON(), nullable=False),
    sa.Column('cost', sa.JSON(), nullable=False),
    sa.Column('ownership', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=96), nullable=False),
    sa.Column('version', sa.String(length=48), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_index(op.f('ix_skill_registry_learner_id'), 'skill_registry', ['learner_id'], unique=False)
    op.create_index('ix_skill_registry_source_enabled', 'skill_registry', ['source', 'enabled'], unique=False)
    op.create_table('transactional_outbox',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('event_key', sa.String(length=192), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('turn_id', sa.String(length=128), nullable=False),
    sa.Column('plan_revision', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('safe_payload', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', name='uq_transactional_outbox_event_key')
    )
    op.create_index('ix_transactional_outbox_pending', 'transactional_outbox', ['published_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactional_outbox_task_id'), 'transactional_outbox', ['task_id'], unique=False)
    op.create_index(op.f('ix_transactional_outbox_turn_id'), 'transactional_outbox', ['turn_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('create_idempotency_key', sa.String(length=192), nullable=True),
    sa.Column('create_payload_digest', sa.String(length=64), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_unread', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.Column('graph_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('intent', sa.JSON(), nullable=False),
    sa.Column('lecture_result', sa.JSON(), nullable=False),
    sa.Column('deck_result', sa.JSON(), nullable=False),
    sa.Column('quiz_result', sa.JSON(), nullable=False),
    sa.Column('adaptive_result', sa.JSON(), nullable=False),
    sa.Column('handoff_result', sa.JSON(), nullable=False),
    sa.Column('user_messages', sa.JSON(), nullable=False),
    sa.Column('visual_result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('current_execution_id', sa.String(length=128), nullable=True),
    sa.Column('latest_execution_id', sa.String(length=128), nullable=True),
    sa.Column('thread_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_current_execution_id'), 'agent_tasks', ['current_execution_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_deleted_at'), 'agent_tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agent_tasks_is_pinned'), 'agent_tasks', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_agent_tasks_latest_execution_id'), 'agent_tasks', ['latest_execution_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_learner_id'), 'agent_tasks', ['learner_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tasks_thread_status'), 'agent_tasks', ['thread_status'], unique=False)
    op.create_index('uq_agent_tasks_learner_create_key', 'agent_tasks', ['learner_id', 'create_idempotency_key'], unique=True)
    op.create_table('decision_trace',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('execution_id', sa.String(length=128), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('goal', sa.JSON(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('selected', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('profile_before', sa.JSON(), nullable=False),
    sa.Column('profile_after', sa.JSON(), nullable=False),
    sa.Column('guardrail_state', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.JSON(), nullable=False),
    sa.Column('replan_of', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'step', name='uq_decision_trace_task_step')
    )
    op.create_index('ix_decision_trace_execution', 'decision_trace', ['execution_id', 'step'], unique=False)
    op.create_index(op.f('ix_decision_trace_learner_id'), 'decision_trace', ['learner_id'], unique=False)
    op.create_index(op.f('ix_decision_trace_replan_of'), 'decision_trace', ['replan_of'], unique=False)
    op.create_index('ix_decision_trace_task_created', 'decision_trace', ['task_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_decision_trace_task_id'), 'decision_trace', ['task_id'], unique=False)
    op.create_table('identity_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issuer', sa.String(length=256), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer', 'subject', name='uq_identity_users_issuer_subject'),
    sa.UniqueConstraint('learner_id', name='uq_identity_users_learner')
    )
    op.create_index(op.f('ix_identity_users_learner_id'), 'identity_users', ['learner_id'], unique=False)
    op.create_table('learner_profiles',
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('learner_id')
    )
    op.create_table('learning_preferences',
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('learner_id')
    )
    op.create_table('learning_profile',
    sa.Column('id', sa.String(length=224), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('knowledge_point_id', sa.String(length=160), nullable=False),
    sa.Column('knowledge_point', sa.String(length=300), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('learning_state', sa.String(length=48), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('my_questions', sa.JSON(), nullable=False),
    sa.Column('recent_performance', sa.JSON(), nullable=False),
    sa.Column('last_studied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_step', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('misconceptions', sa.JSON(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('review_priority', sa.Float(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('source_agent', sa.String(length=96), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('override_flag', sa.Boolean(), nullable=False),
    sa.Column('last_evidence_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'knowledge_point_id', name='uq_learning_profile_learner_point')
    )
    op.create_index('ix_learning_profile_learner_due', 'learning_profile', ['learner_id', 'review_due_at'], unique=False)
    op.create_index(op.f('ix_learning_profile_learner_id'), 'learning_profile', ['learner_id'], unique=False)
    op.create_index('ix_learning_profile_learner_priority', 'learning_profile', ['learner_id', 'review_priority'], unique=False)
    op.create_table('mastery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('concept', sa.String(length=96), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'concept', name='uq_mastery_learner_concept')
    )
    op.create_index(op.f('ix_mastery_learner_id'), 'mastery', ['learner_id'], unique=False)
    op.create_table('misconceptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'tag', name='uq_misconceptions_learner_tag')
    )
    op.create_index(op.f('ix_misconceptions_learner_id'), 'misconceptions', ['learner_id'], unique=False)
    op.create_table('personal_skills',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'name', name='uq_personal_skill_name')
    )
    op.create_index(op.f('ix_personal_skills_learner_id'), 'personal_skills', ['learner_id'], unique=False)
    op.create_table('projection_cursors',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('projection', sa.String(length=96), nullable=False),
    sa.Column('last_event_id', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'projection', name='uq_projection_cursor')
    )
    op.create_index(op.f('ix_projection_cursors_learner_id'), 'projection_cursors', ['learner_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('appearance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', name='uq_workspaces_learner')
    )
    op.create_index(op.f('ix_workspaces_learner_id'), 'workspaces', ['learner_id'], unique=False)
    op.create_table('agent_executions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('turn_id', sa.String(length=128), nullable=True),
    sa.Column('parent_execution_id', sa.String(length=128), nullable=True),
    sa.Column('resumes_execution_id', sa.String(length=128), nullable=True),
    sa.Column('trigger', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('graph_version', sa.String(length=64), nullable=False),
    sa.Column('execution_snapshot', sa.JSON(), nullable=False),
    sa.Column('timeline_spans', sa.JSON(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('schedule_id', sa.String(length=128), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.ForeignKeyConstraint(['parent_execution_id'], ['agent_executions.id'], ),
    sa.ForeignKeyConstraint(['resumes_execution_id'], ['agent_executions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'scheduled_for', name='uq_agent_executions_schedule_slot')
    )
    op.create_index('ix_agent_executions_learner_created', 'agent_executions', ['learner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_executions_learner_id'), 'agent_executions', ['learner_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_schedule_id'), 'agent_executions', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_status'), 'agent_executions', ['status'], unique=False)
    op.create_index('ix_agent_executions_task_created', 'agent_executions', ['task_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_executions_task_id'), 'agent_executions', ['task_id'], unique=False)
    op.create_index('ix_agent_executions_turn_created', 'agent_executions', ['turn_id', 'created_at'], unique=False)
    op.create_table('agent_interactions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('turn_id', sa.String(length=128), nullable=True),
    sa.Column('execution_id', sa.String(length=128), nullable=True),
    sa.Column('agent_run_id', sa.String(length=128), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('presentation', sa.String(length=24), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_interactions_agent_run_id'), 'agent_interactions', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_interactions_execution_id'), 'agent_interactions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_agent_interactions_status'), 'agent_interactions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_interactions_task_id'), 'agent_interactions', ['task_id'], unique=False)
    op.create_index('ix_agent_interactions_task_turn', 'agent_interactions', ['task_id', 'turn_id'], unique=False)
    op.create_index(op.f('ix_agent_interactions_turn_id'), 'agent_interactions', ['turn_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('turn_id', sa.String(length=128), nullable=True),
    sa.Column('execution_id', sa.String(length=128), nullable=False),
    sa.Column('work_item_id', sa.String(length=128), nullable=True),
    sa.Column('parent_agent_run_id', sa.String(length=128), nullable=True),
    sa.Column('provider_id', sa.String(length=96), nullable=False),
    sa.Column('agent_display_name', sa.String(length=200), nullable=False),
    sa.Column('execution_kind', sa.String(length=24), nullable=False),
    sa.Column('capability', sa.String(length=96), nullable=False),
    sa.Column('presentation_role', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_sequence', sa.Integer(), nullable=True),
    sa.Column('end_sequence', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_execution', 'agent_runs', ['execution_id', 'start_sequence'], unique=False)
    op.create_index(op.f('ix_agent_runs_execution_id'), 'agent_runs', ['execution_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_task_id'), 'agent_runs', ['task_id'], unique=False)
    op.create_index('ix_agent_runs_task_turn', 'agent_runs', ['task_id', 'turn_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_turn_id'), 'agent_runs', ['turn_id'], unique=False)
    op.create_index('ix_agent_runs_work_item', 'agent_runs', ['work_item_id'], unique=False)
    op.create_table('agent_schedules',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('source_task_id', sa.String(length=96), nullable=True),
    sa.Column('proposal_id', sa.String(length=128), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('cron', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('inputs_snapshot', sa.JSON(), nullable=False),
    sa.Column('resources_snapshot', sa.JSON(), nullable=False),
    sa.Column('graph_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('approval_scope', sa.String(length=24), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.ForeignKeyConstraint(['source_task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id')
    )
    op.create_index('ix_agent_schedules_due', 'agent_schedules', ['status', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_agent_schedules_learner_id'), 'agent_schedules', ['learner_id'], unique=False)
    op.create_index(op.f('ix_agent_schedules_next_run_at'), 'agent_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_agent_schedules_source_task_id'), 'agent_schedules', ['source_task_id'], unique=False)
    op.create_index(op.f('ix_agent_schedules_status'), 'agent_schedules', ['status'], unique=False)
    op.create_table('agent_task_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('execution_id', sa.String(length=128), nullable=True),
    sa.Column('runtime', sa.JSON(), nullable=False),
    sa.Column('turn_id', sa.String(length=128), nullable=True),
    sa.Column('agent_run_id', sa.String(length=128), nullable=True),
    sa.Column('skill_run_id', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'sequence', name='uq_agent_task_events_sequence')
    )
    op.create_index(op.f('ix_agent_task_events_agent_run_id'), 'agent_task_events', ['agent_run_id'], unique=False)
    op.create_index('ix_agent_task_events_execution', 'agent_task_events', ['execution_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_agent_task_events_execution_id'), 'agent_task_events', ['execution_id'], unique=False)
    op.create_index(op.f('ix_agent_task_events_skill_run_id'), 'agent_task_events', ['skill_run_id'], unique=False)
    op.create_index(op.f('ix_agent_task_events_task_id'), 'agent_task_events', ['task_id'], unique=False)
    op.create_index('ix_agent_task_events_task_sequence', 'agent_task_events', ['task_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_agent_task_events_turn_id'), 'agent_task_events', ['turn_id'], unique=False)
    op.create_table('agent_task_state',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('runtime_status', sa.String(length=32), nullable=False),
    sa.Column('goal_stack', sa.JSON(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('budget', sa.JSON(), nullable=False),
    sa.Column('board', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', name='uq_agent_task_state_task')
    )
    op.create_index(op.f('ix_agent_task_state_learner_id'), 'agent_task_state', ['learner_id'], unique=False)
    op.create_index('ix_agent_task_state_learner_status', 'agent_task_state', ['learner_id', 'runtime_status'], unique=False)
    op.create_table('agent_turns',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('goal_status', sa.String(length=24), nullable=False),
    sa.Column('execution_mode', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'turn_index', name='uq_agent_turns_task_index')
    )
    op.create_index(op.f('ix_agent_turns_status'), 'agent_turns', ['status'], unique=False)
    op.create_index(op.f('ix_agent_turns_task_id'), 'agent_turns', ['task_id'], unique=False)
    op.create_index('ix_agent_turns_task_status', 'agent_turns', ['task_id', 'status'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_artifacts_task_kind', 'artifacts', ['task_id', 'kind'], unique=False)
    op.create_index(op.f('ix_artifacts_workspace_id'), 'artifacts', ['workspace_id'], unique=False)
    op.create_index('ix_artifacts_workspace_updated', 'artifacts', ['workspace_id', 'updated_at'], unique=False)
    op.create_table('learning_evidence',
    sa.Column('id', sa.String(length=192), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('locator', sa.JSON(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('digest', sa.String(length=128), nullable=False),
    sa.Column('knowledge_point', sa.String(length=160), nullable=False),
    sa.Column('signal', sa.String(length=48), nullable=False),
    sa.Column('source_agent', sa.String(length=96), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'evidence_id', name='uq_learning_evidence_task_id')
    )
    op.create_index(op.f('ix_learning_evidence_knowledge_point'), 'learning_evidence', ['knowledge_point'], unique=False)
    op.create_index('ix_learning_evidence_learner_created', 'learning_evidence', ['learner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_learning_evidence_learner_id'), 'learning_evidence', ['learner_id'], unique=False)
    op.create_index('ix_learning_evidence_task', 'learning_evidence', ['task_id', 'seq'], unique=False)
    op.create_index(op.f('ix_learning_evidence_task_id'), 'learning_evidence', ['task_id'], unique=False)
    op.create_index('uq_learning_evidence_learner_seq', 'learning_evidence', ['learner_id', 'seq'], unique=True)
    op.create_table('quiz_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('submission_id', sa.String(length=128), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('per_question', sa.JSON(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('handoff_reason', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', name='uq_quiz_submissions_submission'),
    sa.UniqueConstraint('task_id', name='uq_quiz_submissions_task')
    )
    op.create_index(op.f('ix_quiz_submissions_task_id'), 'quiz_submissions', ['task_id'], unique=False)
    op.create_table('agent_interaction_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interaction_id', sa.String(length=128), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=192), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['agent_interactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interaction_id', 'idempotency_key', name='uq_interaction_answer_key')
    )
    op.create_index(op.f('ix_agent_interaction_answers_interaction_id'), 'agent_interaction_answers', ['interaction_id'], unique=False)
    op.create_table('agent_schedule_runs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('schedule_id', sa.String(length=128), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['agent_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'scheduled_for', name='uq_agent_schedule_runs_slot')
    )
    op.create_index('ix_agent_schedule_runs_schedule', 'agent_schedule_runs', ['schedule_id', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_agent_schedule_runs_schedule_id'), 'agent_schedule_runs', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_agent_schedule_runs_status'), 'agent_schedule_runs', ['status'], unique=False)
    op.create_table('agent_task_state_events',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('agent_task_state_id', sa.String(length=128), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('op', sa.String(length=32), nullable=False),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_task_state_id'], ['agent_task_state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_task_state_id', 'sequence', name='uq_agent_task_state_events_seq')
    )
    op.create_index(op.f('ix_agent_task_state_events_agent_task_state_id'), 'agent_task_state_events', ['agent_task_state_id'], unique=False)
    op.create_table('budget_ledger',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('turn_id', sa.String(length=128), nullable=False),
    sa.Column('plan_revision', sa.Integer(), nullable=False),
    sa.Column('reserved_tokens', sa.Integer(), nullable=False),
    sa.Column('used_tokens', sa.Integer(), nullable=False),
    sa.Column('reserved_heavy', sa.Integer(), nullable=False),
    sa.Column('used_heavy', sa.Integer(), nullable=False),
    sa.Column('reserved_wall_ms', sa.Integer(), nullable=False),
    sa.Column('used_wall_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['agent_turns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'turn_id', 'plan_revision', name='uq_budget_ledger_revision')
    )
    op.create_index(op.f('ix_budget_ledger_task_id'), 'budget_ledger', ['task_id'], unique=False)
    op.create_index(op.f('ix_budget_ledger_turn_id'), 'budget_ledger', ['turn_id'], unique=False)
    op.create_table('candidate_snapshots',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('turn_id', sa.String(length=128), nullable=False),
    sa.Column('plan_revision', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=128), nullable=False),
    sa.Column('capability', sa.String(length=96), nullable=False),
    sa.Column('knowledge_point_id', sa.String(length=128), nullable=False),
    sa.Column('skill_id', sa.String(length=160), nullable=False),
    sa.Column('skill_version', sa.String(length=48), nullable=False),
    sa.Column('skill_checksum', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=96), nullable=False),
    sa.Column('registry_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['agent_turns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'turn_id', 'plan_revision', 'candidate_id', name='uq_candidate_snapshot_binding')
    )
    op.create_index(op.f('ix_candidate_snapshots_candidate_id'), 'candidate_snapshots', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_snapshots_task_id'), 'candidate_snapshots', ['task_id'], unique=False)
    op.create_index(op.f('ix_candidate_snapshots_turn_id'), 'candidate_snapshots', ['turn_id'], unique=False)
    op.create_table('command_inbox',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('turn_id', sa.String(length=128), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('delivery_mode', sa.String(length=24), nullable=False),
    sa.Column('disposition', sa.String(length=24), nullable=False),
    sa.Column('delivery_execution_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=192), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['agent_turns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'idempotency_key', name='uq_command_inbox_task_key')
    )
    op.create_index(op.f('ix_command_inbox_delivery_mode'), 'command_inbox', ['delivery_mode'], unique=False)
    op.create_index(op.f('ix_command_inbox_disposition'), 'command_inbox', ['disposition'], unique=False)
    op.create_index(op.f('ix_command_inbox_task_id'), 'command_inbox', ['task_id'], unique=False)
    op.create_index('ix_command_inbox_task_pending', 'command_inbox', ['task_id', 'consumed_at', 'sequence'], unique=False)
    op.create_index(op.f('ix_command_inbox_turn_id'), 'command_inbox', ['turn_id'], unique=False)
    op.create_table('fact_snapshots',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('turn_id', sa.String(length=128), nullable=False),
    sa.Column('plan_revision', sa.Integer(), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('artifact_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['agent_turns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'turn_id', 'plan_revision', name='uq_fact_snapshot_revision')
    )
    op.create_index(op.f('ix_fact_snapshots_task_id'), 'fact_snapshots', ['task_id'], unique=False)
    op.create_index(op.f('ix_fact_snapshots_turn_id'), 'fact_snapshots', ['turn_id'], unique=False)
    op.create_table('skill_runs',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('agent_run_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('turn_id', sa.String(length=128), nullable=True),
    sa.Column('execution_id', sa.String(length=128), nullable=False),
    sa.Column('skill_id', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=48), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skill_runs_agent_run', 'skill_runs', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_skill_runs_agent_run_id'), 'skill_runs', ['agent_run_id'], unique=False)
    op.create_index('ix_skill_runs_execution', 'skill_runs', ['execution_id'], unique=False)
    op.create_index(op.f('ix_skill_runs_execution_id'), 'skill_runs', ['execution_id'], unique=False)
    op.create_index(op.f('ix_skill_runs_status'), 'skill_runs', ['status'], unique=False)
    op.create_index(op.f('ix_skill_runs_task_id'), 'skill_runs', ['task_id'], unique=False)
    op.create_index('ix_skill_runs_task_turn', 'skill_runs', ['task_id', 'turn_id'], unique=False)
    op.create_index(op.f('ix_skill_runs_turn_id'), 'skill_runs', ['turn_id'], unique=False)
    op.create_table('work_items',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('turn_id', sa.String(length=128), nullable=False),
    sa.Column('work_key', sa.String(length=160), nullable=False),
    sa.Column('plan_revision', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=128), nullable=False),
    sa.Column('capability', sa.String(length=96), nullable=False),
    sa.Column('skill_id', sa.String(length=160), nullable=False),
    sa.Column('skill_version', sa.String(length=48), nullable=False),
    sa.Column('skill_checksum', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=96), nullable=False),
    sa.Column('knowledge_point_id', sa.String(length=128), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=192), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_digest', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_id', sa.String(length=128), nullable=True),
    sa.Column('reserved_tokens', sa.Integer(), nullable=False),
    sa.Column('reserved_heavy', sa.Integer(), nullable=False),
    sa.Column('reserved_wall_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['agent_turns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('turn_id', 'work_key', name='uq_work_items_turn_key')
    )
    op.create_index('ix_work_items_claimable', 'work_items', ['status', 'lease_until'], unique=False)
    op.create_index(op.f('ix_work_items_status'), 'work_items', ['status'], unique=False)
    op.create_index(op.f('ix_work_items_task_id'), 'work_items', ['task_id'], unique=False)
    op.create_index('ix_work_items_task_revision', 'work_items', ['task_id', 'plan_revision'], unique=False)
    op.create_index(op.f('ix_work_items_turn_id'), 'work_items', ['turn_id'], unique=False)
    op.create_table('work_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.String(length=128), nullable=False),
    sa.Column('depends_on_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['work_items.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'depends_on_id', name='uq_work_dependency')
    )
    op.create_index(op.f('ix_work_dependencies_depends_on_id'), 'work_dependencies', ['depends_on_id'], unique=False)
    op.create_index(op.f('ix_work_dependencies_work_id'), 'work_dependencies', ['work_id'], unique=False)
    op.create_table('work_results',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('work_id', sa.String(length=128), nullable=False),
    sa.Column('schema_id', sa.String(length=128), nullable=False),
    sa.Column('safe_summary', sa.Text(), nullable=False),
    sa.Column('artifact_refs', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('output_payload', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_results')
    op.drop_index(op.f('ix_work_dependencies_work_id'), table_name='work_dependencies')
    op.drop_index(op.f('ix_work_dependencies_depends_on_id'), table_name='work_dependencies')
    op.drop_table('work_dependencies')
    op.drop_index(op.f('ix_work_items_turn_id'), table_name='work_items')
    op.drop_index('ix_work_items_task_revision', table_name='work_items')
    op.drop_index(op.f('ix_work_items_task_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_status'), table_name='work_items')
    op.drop_index('ix_work_items_claimable', table_name='work_items')
    op.drop_table('work_items')
    op.drop_index(op.f('ix_skill_runs_turn_id'), table_name='skill_runs')
    op.drop_index('ix_skill_runs_task_turn', table_name='skill_runs')
    op.drop_index(op.f('ix_skill_runs_task_id'), table_name='skill_runs')
    op.drop_index(op.f('ix_skill_runs_status'), table_name='skill_runs')
    op.drop_index(op.f('ix_skill_runs_execution_id'), table_name='skill_runs')
    op.drop_index('ix_skill_runs_execution', table_name='skill_runs')
    op.drop_index(op.f('ix_skill_runs_agent_run_id'), table_name='skill_runs')
    op.drop_index('ix_skill_runs_agent_run', table_name='skill_runs')
    op.drop_table('skill_runs')
    op.drop_index(op.f('ix_fact_snapshots_turn_id'), table_name='fact_snapshots')
    op.drop_index(op.f('ix_fact_snapshots_task_id'), table_name='fact_snapshots')
    op.drop_table('fact_snapshots')
    op.drop_index(op.f('ix_command_inbox_turn_id'), table_name='command_inbox')
    op.drop_index('ix_command_inbox_task_pending', table_name='command_inbox')
    op.drop_index(op.f('ix_command_inbox_task_id'), table_name='command_inbox')
    op.drop_index(op.f('ix_command_inbox_disposition'), table_name='command_inbox')
    op.drop_index(op.f('ix_command_inbox_delivery_mode'), table_name='command_inbox')
    op.drop_table('command_inbox')
    op.drop_index(op.f('ix_candidate_snapshots_turn_id'), table_name='candidate_snapshots')
    op.drop_index(op.f('ix_candidate_snapshots_task_id'), table_name='candidate_snapshots')
    op.drop_index(op.f('ix_candidate_snapshots_candidate_id'), table_name='candidate_snapshots')
    op.drop_table('candidate_snapshots')
    op.drop_index(op.f('ix_budget_ledger_turn_id'), table_name='budget_ledger')
    op.drop_index(op.f('ix_budget_ledger_task_id'), table_name='budget_ledger')
    op.drop_table('budget_ledger')
    op.drop_index(op.f('ix_agent_task_state_events_agent_task_state_id'), table_name='agent_task_state_events')
    op.drop_table('agent_task_state_events')
    op.drop_index(op.f('ix_agent_schedule_runs_status'), table_name='agent_schedule_runs')
    op.drop_index(op.f('ix_agent_schedule_runs_schedule_id'), table_name='agent_schedule_runs')
    op.drop_index('ix_agent_schedule_runs_schedule', table_name='agent_schedule_runs')
    op.drop_table('agent_schedule_runs')
    op.drop_index(op.f('ix_agent_interaction_answers_interaction_id'), table_name='agent_interaction_answers')
    op.drop_table('agent_interaction_answers')
    op.drop_index(op.f('ix_quiz_submissions_task_id'), table_name='quiz_submissions')
    op.drop_table('quiz_submissions')
    op.drop_index('uq_learning_evidence_learner_seq', table_name='learning_evidence')
    op.drop_index(op.f('ix_learning_evidence_task_id'), table_name='learning_evidence')
    op.drop_index('ix_learning_evidence_task', table_name='learning_evidence')
    op.drop_index(op.f('ix_learning_evidence_learner_id'), table_name='learning_evidence')
    op.drop_index('ix_learning_evidence_learner_created', table_name='learning_evidence')
    op.drop_index(op.f('ix_learning_evidence_knowledge_point'), table_name='learning_evidence')
    op.drop_table('learning_evidence')
    op.drop_index('ix_artifacts_workspace_updated', table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_workspace_id'), table_name='artifacts')
    op.drop_index('ix_artifacts_task_kind', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_agent_turns_task_status', table_name='agent_turns')
    op.drop_index(op.f('ix_agent_turns_task_id'), table_name='agent_turns')
    op.drop_index(op.f('ix_agent_turns_status'), table_name='agent_turns')
    op.drop_table('agent_turns')
    op.drop_index('ix_agent_task_state_learner_status', table_name='agent_task_state')
    op.drop_index(op.f('ix_agent_task_state_learner_id'), table_name='agent_task_state')
    op.drop_table('agent_task_state')
    op.drop_index(op.f('ix_agent_task_events_turn_id'), table_name='agent_task_events')
    op.drop_index('ix_agent_task_events_task_sequence', table_name='agent_task_events')
    op.drop_index(op.f('ix_agent_task_events_task_id'), table_name='agent_task_events')
    op.drop_index(op.f('ix_agent_task_events_skill_run_id'), table_name='agent_task_events')
    op.drop_index(op.f('ix_agent_task_events_execution_id'), table_name='agent_task_events')
    op.drop_index('ix_agent_task_events_execution', table_name='agent_task_events')
    op.drop_index(op.f('ix_agent_task_events_agent_run_id'), table_name='agent_task_events')
    op.drop_table('agent_task_events')
    op.drop_index(op.f('ix_agent_schedules_status'), table_name='agent_schedules')
    op.drop_index(op.f('ix_agent_schedules_source_task_id'), table_name='agent_schedules')
    op.drop_index(op.f('ix_agent_schedules_next_run_at'), table_name='agent_schedules')
    op.drop_index(op.f('ix_agent_schedules_learner_id'), table_name='agent_schedules')
    op.drop_index('ix_agent_schedules_due', table_name='agent_schedules')
    op.drop_table('agent_schedules')
    op.drop_index('ix_agent_runs_work_item', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_turn_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_task_turn', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_task_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_execution_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_execution', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agent_interactions_turn_id'), table_name='agent_interactions')
    op.drop_index('ix_agent_interactions_task_turn', table_name='agent_interactions')
    op.drop_index(op.f('ix_agent_interactions_task_id'), table_name='agent_interactions')
    op.drop_index(op.f('ix_agent_interactions_status'), table_name='agent_interactions')
    op.drop_index(op.f('ix_agent_interactions_execution_id'), table_name='agent_interactions')
    op.drop_index(op.f('ix_agent_interactions_agent_run_id'), table_name='agent_interactions')
    op.drop_table('agent_interactions')
    op.drop_index('ix_agent_executions_turn_created', table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_task_id'), table_name='agent_executions')
    op.drop_index('ix_agent_executions_task_created', table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_status'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_schedule_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_learner_id'), table_name='agent_executions')
    op.drop_index('ix_agent_executions_learner_created', table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index(op.f('ix_workspaces_learner_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_projection_cursors_learner_id'), table_name='projection_cursors')
    op.drop_table('projection_cursors')
    op.drop_index(op.f('ix_personal_skills_learner_id'), table_name='personal_skills')
    op.drop_table('personal_skills')
    op.drop_index(op.f('ix_misconceptions_learner_id'), table_name='misconceptions')
    op.drop_table('misconceptions')
    op.drop_index(op.f('ix_mastery_learner_id'), table_name='mastery')
    op.drop_table('mastery')
    op.drop_index('ix_learning_profile_learner_priority', table_name='learning_profile')
    op.drop_index(op.f('ix_learning_profile_learner_id'), table_name='learning_profile')
    op.drop_index('ix_learning_profile_learner_due', table_name='learning_profile')
    op.drop_table('learning_profile')
    op.drop_table('learning_preferences')
    op.drop_table('learner_profiles')
    op.drop_index(op.f('ix_identity_users_learner_id'), table_name='identity_users')
    op.drop_table('identity_users')
    op.drop_index(op.f('ix_decision_trace_task_id'), table_name='decision_trace')
    op.drop_index('ix_decision_trace_task_created', table_name='decision_trace')
    op.drop_index(op.f('ix_decision_trace_replan_of'), table_name='decision_trace')
    op.drop_index(op.f('ix_decision_trace_learner_id'), table_name='decision_trace')
    op.drop_index('ix_decision_trace_execution', table_name='decision_trace')
    op.drop_table('decision_trace')
    op.drop_index('uq_agent_tasks_learner_create_key', table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_thread_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_learner_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_latest_execution_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_is_pinned'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_deleted_at'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_current_execution_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_transactional_outbox_turn_id'), table_name='transactional_outbox')
    op.drop_index(op.f('ix_transactional_outbox_task_id'), table_name='transactional_outbox')
    op.drop_index('ix_transactional_outbox_pending', table_name='transactional_outbox')
    op.drop_table('transactional_outbox')
    op.drop_index('ix_skill_registry_source_enabled', table_name='skill_registry')
    op.drop_index(op.f('ix_skill_registry_learner_id'), table_name='skill_registry')
    op.drop_table('skill_registry')
    op.drop_table('learners')
    # ### end Alembic commands ###
