export const PRODUCT_LOCALE = 'zh-CN' as const

export const workspaceCopy = {
  common: {
    actions: {
      cancel: '取消',
      close: '关闭',
      create: '创建',
      delete: '删除',
      download: '下载',
      move: '移动',
      refresh: '刷新',
      rename: '重命名',
      retry: '重试',
      save: '保存',
      search: '搜索',
      selectAll: '全选',
    },
    columns: {
      created: '创建时间',
      name: '名称',
      owner: '所有者',
      size: '大小',
      status: '状态',
      type: '类型',
      updated: '最后更新',
    },
    filters: { all: '全部', clear: '清除筛选' },
    states: {
      empty: '暂无内容',
      loading: '正在加载…',
      noResults: '没有找到结果',
      unavailable: '暂时无法使用',
    },
    errors: {
      conflict: '内容已发生变化，请刷新后重试。',
      connectionFailed: '网络连接失败，请稍后重试。',
      deleteFailed: '删除失败，请稍后重试。',
      loadFailed: '加载失败，请稍后重试。',
      notFound: '未找到所需内容，可能已被删除。',
      payloadTooLarge: '内容过大，请缩小后重试。',
      permissionDenied: '你没有执行此操作的权限。',
      rateLimited: '操作过于频繁，请稍后重试。',
      saveFailed: '保存失败，请稍后重试。',
      unexpected: '操作失败，请稍后重试。',
      uploadFailed: '上传失败，请稍后重试。',
    },
    accessibility: {
      path: '路径',
      pinned: '已置顶',
      selectAll: '全选',
      selectRow: '选择此行',
    },
  },
  resources: {
    actions: {
      archive: '归档',
      delete: '删除',
      deleting: '正在删除…',
      discardChanges: '放弃更改',
      edit: '编辑',
      importCsv: '导入 CSV',
      moveTo: '移动到',
      newBase: '新建知识库',
      newFile: '新建文件',
      newFolder: '新建文件夹',
      newTable: '新建表格',
      pin: '置顶',
      rename: '重命名',
      preview: '预览',
      share: '分享',
      unpin: '取消置顶',
      upload: '上传',
    },
    states: {
      empty: '空',
      fewRows: '少量数据',
      manyRows: '大量数据',
    },
    files: {
      title: '文件',
      description: '管理工作区中的文件和学习资料。',
      empty: '还没有文件',
      searchPlaceholder: '搜索文件…',
      columns: { name: '名称', size: '大小', type: '类型', created: '创建时间' },
      loadFailedTitle: '无法加载文件',
      dropToUpload: '松开以上传',
      dropToUploadHint: '在此放下文件，将其添加到当前工作区',
    },
    knowledge: {
      title: '知识库',
      description: '整理并检索用于学习的知识资料。',
      empty: '还没有知识库',
      searchPlaceholder: '搜索知识库…',
      columns: { name: '名称', documents: '文档', tokens: 'Token', created: '创建时间' },
      loadFailedTitle: '无法加载知识库',
    },
    tables: {
      title: '表格',
      description: '组织结构化的学习数据。',
      empty: '还没有表格',
      searchPlaceholder: '搜索表格…',
      columns: {
        name: '名称',
        columns: '列数',
        rows: '行数',
        created: '创建时间',
        updated: '最后更新',
      },
      loadFailedTitle: '无法加载表格',
    },
    logs: { title: '日志' },
  },
  home: {
    resourceLoadFailed: '无法打开此资源，请稍后重试。',
    voiceInputFailed: '语音输入失败，请稍后重试。',
  },
  skills: {
    fields: { name: '名称', description: '描述', content: '内容' },
  },
} as const
