"""Persistence boundary used by the runtime domain."""

from __future__ import annotations

from typing import Any, Protocol

from ..domain.learning_profile import ProfileChange, ProfileDelta


class RuntimeStatePort(Protocol):
    async def get_agent_task_state(self, task_id: str) -> dict[str, Any] | None: ...

    async def set_runtime_status(self, task_id: str, status: str) -> dict[str, Any]: ...

    async def projection_cursor(self, learner_id: str) -> int: ...

    async def evidence_after(
        self, learner_id: str, after: int, *, limit: int
    ) -> list[dict[str, Any]]: ...

    async def profile_for(self, learner_id: str) -> list[dict[str, Any]]: ...

    async def advance_projection_cursor(self, learner_id: str, sequence: int) -> None: ...

    async def apply_profile_deltas(self, deltas: list[ProfileDelta]) -> list[ProfileChange]: ...

    async def next_decision_step(self, task_id: str) -> int: ...

    async def record_decision(self, **fields: Any) -> dict[str, Any]: ...

    async def update_decision_outcome(self, decision_id: str, outcome: dict[str, Any]) -> None: ...
